### ISSUE TITLE
Video survey doesn't work without Kademi survey app

### ISSUE THREAD

**Issue by Uafinder** [anhnt/videosurvey#1]
![image](https://cloud.githubusercontent.com/assets/1945230/14794761/2343efba-0b2e-11e6-9eca-22fff459c2d2.png)
![image](https://cloud.githubusercontent.com/assets/1945230/14794769/2d33be92-0b2e-11e6-9070-482359816c13.png)
It should work when VideoSurvey app is enabled

**Comment by anhnt** [comment]
looks like permission issue :)
