### ISSUE TITLE
IE: Cannot catch a webcam and microphone control

### ISSUE THREAD

**Issue by Uafinder** [anhnt/videosurvey#3]
![image](https://cloud.githubusercontent.com/assets/1945230/14795161/dcb258c8-0b2f-11e6-929d-03a846bd4e16.png)
Pushing to begin camera using doesn't causing webcam and microphone activation,

**Comment by anhnt** [comment]
Yeah, IE 11 doesnt support getUserMedia api. Please use Edge or Chrome, FF instead
