### ISSUE TITLE
One click to start recording

### ISSUE THREAD

**Issue by bradmac** [anhnt/videosurvey#9]
Currently the user has to
- click "Record your answer" to open modal
- Click the button inside the video control to activate the camera
- Click the record circle to actually record

Please try to make that a single click to open the modal and begin recording.

**Comment by anhnt** [comment]
i think it should open camera automatically but let users decide when they start recording. i.e they can see their cravat is not good looking and just adjust it before actually start recording :)

**Comment by bradmac** [comment]
Sounds good. Two clicks then :)

**Comment by anhnt** [comment]
done :)
